### ISSUE TITLE
Avoid using storetheindex specific config data structures for public clients

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/indexer-reference-provider#36]
`IngestClient` expects as an argument an `Identity` config data structure. This means that we need to generate an ad-hoc storetheindex identity config in refere-provider to make an `IndexContent` call from the provider. We should consider removing this dependency from storetheindex specific config data structures.

https://github.com/filecoin-project/indexer-reference-provider/blob/78768e2546a7f81fe7c6237644f5598a83ea5258/core/engine/engine.go#L174

**Comment by gammazero** [comment]
Fixed in #40
