### ISSUE TITLE
Importing the same car file with the same metadata should not generate a new advertisement

### ISSUE THREAD

**Issue by gammazero** [filecoin-project/indexer-reference-provider#75]
Each time a car file is imported, this results in a different advertisement CID.  This is preventing the indexer from determining that it has already ingested the advertised indexes.

The reason that the CID is different is that each new advertisement links to the previous and the CID is calculated over the advertisement data and its link to the previous.  What needs to happen is that the previous advertisement needs to be looked up by context ID, and if a previous advertisement exists for that context ID (coming from car supplier) and the previous advertisement metadata is equal to the current metadata, then the import request should be ignored.

Note: The context ID comes from the car supplier, which comes from the import request, which is a hash of the car file path.  The metadata also originates from the import request.

**Comment by willscott** [comment]
confirming you mean the root cid in the advertisement is different. if so, it may be an ordering issue?
