### ISSUE TITLE
Add endpoint to admin server to remove content by context ID

### ISSUE THREAD

**Issue by gammazero** [filecoin-project/indexer-reference-provider#77]
The admin server needs a new endpoint for removing car content.  This new `admin/remove/car` endpoint will complement the existing `admin/import/car` endpoint, and will take a contextID or a file path as input.  The file path is used to generate the contextID if contextID is not supplied.

Invoking this endpoint must result in a remove advertisement when previously imported content is removed from the provider.

**Comment by masih** [comment]
> The file path is used to generate the contextID if contextID is not supplied.

CAR supplier takes context ID explicitly as the key associated to a path. 
Deferring removal by path alone.
